### PR TITLE
Feature/ftg high freqs

### PR DESCRIPTION
**Pull request by buzinsky**
Printed wrong FTG freqs to root file (that was the only issue I see)

### CODE REVIEW

**Comment by pslocum** [comment]
It might be that these spectrogram start frequencies are not right either.  From the config file, it looks like the first track should start at 6 MHz (106 MHz on the spectrogram), but it seems like it is looking low by about 100 MHz?

**Comment by buzinsky** [comment]
ok I am able to get the expected behavior. I dont see whats wrong with yours...
image

**Comment by pslocum** [comment]
On the feature/FTGHighFreqs branch, I simulate one 90 degree FTG track with the Root file outputs below.  In the no-noise spectrogram I am not seeing a track at 10 MHz (110 MHz on Katydid spectrogram).  Could we maybe have overlapping constraints coming from the same config file, or is there some other reason I should not be seeing a track at 110 MHz (FTG config file below)?

image
image

`    "fake-track":
    {
    "random-seed": 1,
    "magnetic-field": 0.9578186017836624,
    "domain": "time",
    "signal-power": 1e-9, 
    "start-frequency-max": 25.90648828125e9,
    "start-frequency-min": 25.906e9,
    "lo-frequency": 25.9e9,
    "start-time-min": 0.00,
    "start-time-max": 0.014,
    "start-vphase": 0.0,
    "slope-mean": 0.350,
    "slope-std": 0.053,   
    "track-length-mean": 1.82417e-2,    
    "hydrogen-fraction": 0.5,
    "start-pitch-min": 90.0,
    "ntracks-mean": 6.0,
    "pitch-correction": 1
    },
   `

**Comment by buzinsky** [comment]
``` "signal-power": 1.0e-15,
    "start-frequency-max": 20.053e9,
    "start-frequency-min": 20.049e9,
    "start-vphase": 0.0,
    "slope-mean": 0.6,
    "slope-std": 0.025,
    "start-time-min": 0.001,
    "start-time-max": 0.003,
    "lo-frequency": 20.0e9,
    "track-length-mean": 0.002,
    "ntracks-mean": 5.0,
    "random-seed": 15,
    "n-events": 1,
    "hydrogen-fraction":1,
    "pitch-correction":0,
    "root-filename": "LocustEvent.root"```

**Pull request merged**
